config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resource :shopping_cart, only: [:show]
  resources :cart_items, only: [:destroy] do
    patch :add, on: :collection
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :items, class_name: 'CartItem'

  def total
    if items.any?
      items.map(&:total).reduce(:+)
    else
      0
    end
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart, counter_cache: :items_count
  belongs_to :product

  validates_presence_of :cart, :product
  validates_numericality_of :quantity, greater_than: 0, only_integer: true

  delegate :name, :price, to: :product

  def total
    quantity * price
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :shopping_cart

  def shopping_cart
    if session[:cart_id].present?
      Cart.includes(:items).find(session[:cart_id])
    else
      cart = Cart.create
      session[:cart_id] = cart.id
      cart
    end
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def add 
    item = shopping_cart.items.find_or_initialize_by(product_id: params[:product_id])
    if item.new_record?
      item.quantity = 1
      item.save
    else
      item.increment!(:quantity)
    end
  end

  def destroy
    item = shopping_cart.items.find(params[:id])
    item.destroy
    @items = shopping_cart.items
    @total = shopping_cart.total
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(name: :asc)
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  def show
    @items = shopping_cart.items
    @total = shopping_cart.total
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cart_items/add.js.erb
$('#shopping-cart').html('<%= j render('layouts/shopping_cart') %>')

app/views/cart_items/destroy.js.erb
$('#shopping-cart').html('<%= j render('layouts/shopping_cart') %>')
$('#shopping-cart-items').html('<%= j render("shopping_carts/items_#{@items.any?}", items: @items, total: @total) %>')

app/views/layouts/_shopping_cart.html.erb
<%= link_to shopping_cart_path, class: 'shopping-cart-link' do %>
  <span class="glyphicon glyphicon-shopping-cart"></span>
  <span><%= t('shopping_carts.quantity', count: shopping_cart.items_count) %></span>
  <span>(<%= number_to_currency(shopping_cart.total) %>)</span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='pt-BR'>
<head>
  <title><%= t('system_name') %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <main class="container">
    <div class="row">
      <div class="col-xs-6 text-left">
        <h1><%= link_to t('system_name'), root_path, class: 'system-title' %></h1>
      </div>

      <div id="shopping-cart" class="col-xs-6 text-right">
        <%= render 'layouts/shopping_cart' %>
      </div>
    </div>

    <hr/>

    <%= yield %>
  </main>

</body>
</html>

app/views/products/index.html.erb
<% @products.each do |product| %>
  <div class="col-xs-6 col-md-3 product">
    <%= image_tag "#{product.name}.jpg", class: 'picture' %>
    <span class="product-name"><%= product.name %></span>
    <div>
      <span class="product-price"><%= number_to_currency(product.price) %></span>

      <div class="add-cart-button">
        <%= form_tag add_cart_items_path, method: :patch, remote: true do %>
          <%= hidden_field_tag :product_id, product.id %>
          <%= button_tag type: 'submit', class: 'btn btn-success' do %>
            <span class="glyphicon glyphicon-shopping-cart"></span> <%= t('products.index.add') %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shopping_carts/_items_false.html.erb
<div class="row">
  <div class="col-xs-12 text-center">
    <span class="empty-cart"><%= t('shopping_carts.show.empty') %></span>
  </div>
</div>

app/views/shopping_carts/_items_true.html.erb
<table class="table">
  <caption>Seu carrinho de compras</caption>
  <thead>
    <tr>
      <td colspan="2"><%= Product.human_attribute_name(:name) %></td>
      <td><%= CartItem.human_attribute_name(:quantity) %></td>
      <td><%= CartItem.human_attribute_name(:price) %></td>
      <td><%= CartItem.human_attribute_name(:total) %></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% items.each do |item| %>
      <tr>
        <td><%= image_tag "#{item.name}.jpg", class: 'cart-picture' %></td>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency(item.price) %></td>
        <td><%= number_to_currency(item.total) %></td>
        <td>
          <%= link_to cart_item_path(item), method: :delete, remote: true, class: "btn btn-danger" do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="4"><%= Cart.human_attribute_name(:total) %></td>
      <td colspan="2"><%= number_to_currency(total) %></td>
    </tr>
  </tbody>
</table>

app/views/shopping_carts/show.html.erb
<div id="shopping-cart-items">
  <%= render "items_#{@items.any?}", items: @items, total: @total %>
</div>